/*
 * creator : Latief Al Amin
 * e-mail  : al _amin_o4_032@yahoo.co.id
 * create  : Oct 2, 2010
 */

/*
 * JpFrameTest.java
 *
 * Created on Aug 23, 2010, 10:15:46 AM
 */

package org.prambananswing;

/**
 *
 * @author Latief Al Amin
 */
public class JpFrameTableTest extends javax.swing.JFrame {

    /** Creates new form JpFrameTest */
    public JpFrameTableTest() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPPanel1 = new org.prambananswing.swing.panel.JPPanel();
        jPScrollPane1 = new org.prambananswing.swing.scrollpane.JPScrollPane();
        jPTable1 = new org.prambananswing.swing.table.JPTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPScrollPane1.setOpaque(false);

        jPTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jPTable1.setOpaque(false);
        jPScrollPane1.setViewportView(jPTable1);

        javax.swing.GroupLayout jPPanel1Layout = new javax.swing.GroupLayout(jPPanel1);
        jPPanel1.setLayout(jPPanel1Layout);
        jPPanel1Layout.setHorizontalGroup(
            jPPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
                .addGap(11, 11, 11))
        );
        jPPanel1Layout.setVerticalGroup(
            jPPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JpFrameTableTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.prambananswing.swing.panel.JPPanel jPPanel1;
    private org.prambananswing.swing.scrollpane.JPScrollPane jPScrollPane1;
    private org.prambananswing.swing.table.JPTable jPTable1;
    // End of variables declaration//GEN-END:variables

}
